FROM node:16.13.2
COPY package*.json ./
RUN npm i
COPY . .

ENV PORT=5000
ENV DB_NAME=susu-3dmap
ENV DB_USER=postgres
ENV DB_PASSWORD=1
ENV DB_HOST=host.docker.internal
ENV DB_PORT=5432

EXPOSE ${PORT}
CMD ["npm", "run", "dev"]